{"name": "test_greater_than_5[4]", "status": "failed", "statusDetails": {"message": "AssertionError: Given number is less than 5\nassert False", "trace": "self = <test_demo_report.TestDemoOne object at 0x000002436C84C7D0>, data = 4\n\n    @pytest.mark.parametrize('data', [8, 4, 9])\n    def test_greater_than_5(self, data):\n        if data > 5:\n            assert True\n        else:\n>           assert False, 'Given number is less than 5'\nE           AssertionError: Given number is less than 5\nE           assert False\n\ntest_demo_report.py:9: AssertionError"}, "parameters": [{"name": "data", "value": "4"}], "start": 1693137524150, "stop": 1693137524150, "uuid": "a7f1ae26-4449-4fb9-8a5f-b865bf782103", "historyId": "aed415f73784aa8e19a1197ab6d13f90", "testCaseId": "4fbed66b7245c521df532c80916faaa7", "fullName": "test_demo_report.TestDemoOne#test_greater_than_5", "labels": [{"name": "suite", "value": "test_demo_report"}, {"name": "subSuite", "value": "TestDemoOne"}, {"name": "host", "value": "DESKTOP-G7A3TQO"}, {"name": "thread", "value": "35660-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_demo_report"}]}